# https://github.com/serverless-components/tencent-scf/blob/master/docs/configure.md

#组件信息
component: scf
name: bilibili_tool

#组件参数配置
inputs:
  name: ${name}_scf
  namespace: default
  enableRoleAuth: false
  src: ./bin/publish/
  handler: index.main_handler
  runtime: CustomRuntime
  region: ap-guangzhou # 函数所在区域，默认广州
  description: This is a function in ${app} application.
  memorySize: 128
  initTimeout: 30
  timeout: 86400
  asyncRunEnable: true
  traceEnable: true
  events: # 根据自己的需要修改
    - timer: # 每日任务触发器
        parameters:
          name: DailyTask
          cronExpression: "0 30 12 * * * *"
          enable: true
          argument: Daily
    - timer: # 天选抽奖触发器
        parameters:
          name: LiveLotteryTask
          cronExpression: "0 0 */4 * * * *"
          enable: true
          argument: LiveLottery
    - timer: # 自动取关
        parameters:
          name: UnfollowBatchedTask
          cronExpression: "0 0 0 * * MON *"
          enable: true
          argument: UnfollowBatched
  environment:
    variables: # 根据自己的需要修改
      Ray_BiliBiliCookies__1: buvid3=B08ED378-1920-9FEB-7F3F-757A9904D61729124infoc; i-wanna-go-back=-1; _uuid=FDB1A1BA-1B8A-B6110-FAFB-5D42838117C428086infoc; buvid4=24D97FF2-6DD8-6A9E-4594-89B06EDA443D30488-022082023-xREVEdt9gFwaqge6KTnv8A%3D%3D; buvid_fp_plain=undefined; DedeUserID=428198059; DedeUserID__ckMd5=4a4444e67663cfef; b_ut=5; buvid_fp=f6ba43ee7818b0b43bbfe9f75b81f698; rpdid=|(J~R~|~JYJ~0J'uYYu|mk|J); LIVE_BUVID=AUTO5116610944609103; nostalgia_conf=-1; fingerprint=f6ba43ee7818b0b43bbfe9f75b81f698; fingerprint3=1fe79badfcc6fcc6d23bf4524b1c2edd; PVID=1; SESSDATA=bad08b0c%2C1676823801%2C42790%2A81; bili_jct=19cd452e18b2f66202be93a8f60984c8; b_lsid=33E1910C5_182CDD15D48; sid=56e6asni; bp_video_offset_428198059=697810268685598800; b_timer=%7B%22ffp%22%3A%7B%22333.1007.fp.risk_B08ED378%22%3A%22182CDD162A9%22%2C%22333.337.fp.risk_B08ED378%22%3A%22182CDD184AC%22%2C%22333.788.fp.risk_B08ED378%22%3A%22182CDD1D151%22%2C%22333.400.fp.risk_B08ED378%22%3A%22182CDD81035%22%7D%7D; CURRENT_FNVAL=16; innersign=0 # cookie，必填
